DPTS/DPTS.Web/Models/StateProvinceViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace DPTS.Web.Models
{
    public class StateProvinceViewModel
    {
        public StateProvinceViewModel()
        {
            AvailableCountry = new List<SelectListItem>();
        }
        public int Id { get; set; }

        [Display(Name = "Country")]
        public int CountryId { get; set; }

        public string CountryName { get; set; }

        [Required]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Display(Name = "Abbreviation")]
        public string Abbreviation { get; set; }

        [Display(Name = "Published")]
        public bool Published { get; set; }

        [Display(Name = "Display Order")]
        public int DisplayOrder { get; set; }

        [Display(Name = "Date Created")]
        public DateTime DateCreated { get; set; }

        [Display(Name = "Date Updated")]
        public DateTime DateUpdated { get; set; }

        public IList<SelectListItem> AvailableCountry { get; set; }
    }
}

DPTS/DPTS.Web/Controllers/StateProvinceController.cs
using DPTS.Web.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using DPTS.Domain.Core.Country;
using DPTS.Domain.Core.StateProvince;
using DPTS.Domain.Entities;

namespace DPTS.Web.Controllers
{
    [Authorize]
    public class StateProvinceController : BaseController
    {
        #region Fields

        private readonly IStateProvinceService _stateProvinceService;
        private readonly ICountryService _countryService;

        #endregion

        #region Contructor

        public StateProvinceController(IStateProvinceService stateProvinceService, ICountryService countryService)
        {
            _stateProvinceService = stateProvinceService;
            _countryService = countryService;
        }

        #endregion

        #region Utilities

        public IList<SelectListItem> GetCountryList()
        {
            var countries = _countryService.GetAllCountries(true);
            List<SelectListItem> typelst = new List<SelectListItem>
            {
                new SelectListItem
                {
                    Text = "Select",
                    Value = "0"
                }
            };
            typelst.AddRange(countries.ToList().Select(type => new SelectListItem
            {
                Text = type.Name,
                Value = type.Id.ToString()
            }));
            return typelst;
        }

        #endregion

        #region Methods

        public ActionResult List()
        {
            var countries = _stateProvinceService.GetAllStateProvince();
            var model = countries.Select(c => new StateProvinceViewModel
            {
                Id = c.Id,
                Name = c.Name,
                CountryName = _countryService.GetCountryById(c.CountryId).Name,
                DisplayOrder = c.DisplayOrder,
                Abbreviation = c.Abbreviation,
                Published = c.Published,
                CountryId = c.CountryId
            }).ToList();
            return View(model);
        }

        public ActionResult Create()
        {
            var model = new StateProvinceViewModel();
            model.AvailableCountry = GetCountryList();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(StateProvinceViewModel model)
        {
            try
            {
                if (model.CountryId == 0)
                    ModelState.AddModelError("", "select country");

                if (ModelState.IsValid)
                {
                    var stateProvince = new StateProvince
                    {
                        Name = model.Name,
                        Published = model.Published,
                        DisplayOrder = model.DisplayOrder,
                        Abbreviation = model.Abbreviation,
                        CountryId = model.CountryId
                    };
                    _stateProvinceService.InsertStateProvince(stateProvince);
                    SuccessNotification("State added successfully.");
                    return RedirectToAction("List");
                }
                model.AvailableCountry = GetCountryList();
                ErrorNotification("Fill required fields");
                return View(model);
            }
            catch (System.Exception)
            {
                throw;
            }
        }

        public ActionResult Edit(int Id)
        {
            try
            {
                if (!IsValidateId(Id))
                    return HttpNotFound();

                var stateProvince = _stateProvinceService.GetStateProvinceById(Id);
                if (stateProvince == null)
                    return HttpNotFound();

                var model = new StateProvinceViewModel
                {
                    Id = stateProvince.Id,
                    Name = stateProvince.Name,
                    CountryName = _countryService.GetCountryById(stateProvince.CountryId).Name,
                    DisplayOrder = stateProvince.DisplayOrder,
                    Published = stateProvince.Published,
                    CountryId = stateProvince.CountryId,
                    Abbreviation = stateProvince.Abbreviation,
                    AvailableCountry = GetCountryList()
                };
                return View(model);
            }
            catch { throw; }
        }

        [HttpPost]
        public ActionResult Edit(StateProvinceViewModel model)
        {
            if (ModelState.IsValid)
            {
                var stateProvince = _stateProvinceService.GetStateProvinceById(model.Id);
                stateProvince.Id = model.Id;
                stateProvince.Name = model.Name;
                stateProvince.DisplayOrder = model.DisplayOrder;
                stateProvince.Published = model.Published;
                stateProvince.CountryId = model.CountryId;
                stateProvince.Abbreviation = model.Abbreviation;
                _stateProvinceService.UpdateStateProvince(stateProvince);
                SuccessNotification("State updated successfully.");
                return RedirectToAction("List");
            }
            model.AvailableCountry = GetCountryList();
            ErrorNotification("Fill required fields");
            return View(model);
        }

        public ActionResult DeleteConfirmed(int id)
        {
            var stateProvince = _stateProvinceService.GetStateProvinceById(id);
            if (stateProvince != null)
                _stateProvinceService.DeleteStateProvince(stateProvince);


            return Content("Deleted");
        }

        #endregion
    }
}

DPTS/DPTS.Web/Views/StateProvince/Create.cshtml
@using DPTS.Web.Models
@model StateProvinceViewModel
@{
    ViewBag.Title = "add - country";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Add New</h1>
            <div class="pull-right" style="margin-top:-68px">
                <button type="submit" name="save" class="btn bg-blue" style="background-color:#0073b7;color:white">
                    <i class="fa fa-floppy-o"></i>
                    Save
                </button>
            </div>
           @Html.ActionLink("Back to List", "List")
        </div>
        <!-- /.col-lg-12 -->
    </div>
    @Html.Partial("_CreateOrUpdate", Model)
}

DPTS/DPTS.Web/Views/StateProvince/Edit.cshtml
@using DPTS.Web.Models
@model StateProvinceViewModel
@{
    ViewBag.Title = "add - country";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Edit - @Model.Name
            </h1>
            <div class="pull-right" style="margin-top:-68px">
                <button type="submit" name="save" class="btn bg-blue" style="background-color:#0073b7;color:white">
                    <i class="fa fa-floppy-o"></i>
                    Save
                </button>
            </div>
            @Html.ActionLink("Back to List", "List")
        </div>
    </div>
    @Html.Partial("_CreateOrUpdate", Model)
}

DPTS/DPTS.Web/Views/StateProvince/List.cshtml
@using DPTS.Web.Models
@model IEnumerable<StateProvinceViewModel>
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
    <link href="~/Content/Admin/vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">
    <!-- DataTables Responsive CSS -->
    <link href="~/Content/Admin/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet">

    int i = 1;
}

<div class="row">
    <div class="col-lg-12">
        <div class="pull-right-button">
            <a href="@Url.Action("Create","StateProvince")" class="btn btn-primary">
                <i class="fa fa-plus-square"></i>
                Add new
            </a>
        </div>

        <h1 class="page-header">State Province</h1>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                State Province
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table table-striped table-bordered table-hover" id="Spacility-list">
                                <thead>
                                    <tr>
                                        <th>
                                            Name
                                        </th>
                                        <th>
                                            Country
                                        </th>
                                        <th>
                                            Abbravation
                                        </th>
                                        <th>
                                            Display Order
                                        </th>
                                        <th>
                                            Published
                                        </th>
                                        <th>
                                            Action
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        if (i % 2 != 0)
                                        {
                                            <tr class="odd gradeX">
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Name)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.CountryName)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Abbreviation)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.DisplayOrder)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Published)
                                                </td>
                                                <td>
                                                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                                    <a href="#" data-toggle="modal" data-target="#myModal" onclick="deleterecord(@item.Id,'StateProvince')">Delete</a>
                                                </td>
                                            </tr>
                                        }
                                        else
                                        {
                                            <tr class="even gradeA">
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Name)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.CountryName)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Abbreviation)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.DisplayOrder)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Published)
                                                </td>
                                                <td>
                                                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                                    <a href="#" data-toggle="modal" data-target="#myModal" onclick="deleterecord(@item.Id,'StateProvince')">Delete</a>
                                                </td>
                                            </tr>
                                        }
                                        i++;
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

DPTS/DPTS.Web/Views/StateProvince/_CreateOrUpdate.cshtml
@using DPTS.Web.Models
@model StateProvinceViewModel

@Html.HiddenFor(model => model.Id)

<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-6">
                    <form role="form">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name)
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.CountryId)
                            @Html.DropDownListFor(model => model.CountryId, Model.AvailableCountry,new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Abbreviation)
                            @Html.EditorFor(model => model.Abbreviation, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.DisplayOrder)
                            @Html.EditorFor(model => model.DisplayOrder, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Published)
                            @Html.EditorFor(model => model.Published, new { @class = "form-control" })
                        </div>
                        @if (Model.Id > 0)
                        {
                            <div class="form-group">
                                    @Html.LabelFor(model => model.DateUpdated)
                                    @Html.DisplayFor(model => model.DateCreated)
                            </div>
                        }
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>