DPTS/DPTS.Web/Controllers/AdminBlogController.cs
using DPTS.Common.Kendoui;
using DPTS.Domain.Common;
using DPTS.Domain.Entities;
using DPTS.Services;
using DPTS.Web.AppInfra;
using DPTS.Web.Models;
using RestSharp.Extensions.MonoHttp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace DPTS.Web.Controllers
{
    public partial class AdminBlogController : BaseController
    {
        #region Fields

        private readonly IBlogService _blogService;
        // private readonly IUrlRecordService _urlRecordService;
        private static TimeZoneInfo INDIAN_ZONE_C = TimeZoneInfo.FindSystemTimeZoneById("India Standard Time");

        #endregion

        #region Ctor

        public AdminBlogController(IBlogService blogService)
        {
            this._blogService = blogService;
        }
        #endregion

        #region Utilities

        #endregion

        #region Blog posts

        public virtual ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public virtual ActionResult List()
        {
          //  var model = new AdminBlogPostListModel();

            //stores
            //model.AvailableStores.Add(new SelectListItem { Text = _localizationService.GetResource("Admin.Common.All"), Value = "0" });
            //foreach (var store in _storeService.GetAllStores())
              //  model.AvailableStores.Add(new SelectListItem { Text = store.Name, Value = store.Id.ToString() });

            return View();
        }
      

        [HttpPost]
        public virtual ActionResult List(DataSourceRequest command)
        {
            var blogPosts = _blogService.GetAllBlogPosts(null, null, command.Page - 1, command.PageSize, true);
            var gridModel = new DataSourceResult
            {
                Data = blogPosts.Select(x =>
                {
                    var m = new AdminBlogPostModel();
                    m.AllowComments = x.AllowComments;
                    m.BodyOverview = x.BodyOverview;
                    m.Tags = x.Tags;
                    m.Title = x.Title;
                    m.Id = x.Id;

                    //little performance optimization: ensure that "Body" is not returned
                    m.Body = "";
                    if (x.StartDateUtc.HasValue)
                        m.StartDate = ConvertToUserTime(x.StartDateUtc.Value, DateTimeKind.Utc);
                    if (x.EndDateUtc.HasValue)
                        m.EndDate = ConvertToUserTime(x.EndDateUtc.Value, DateTimeKind.Utc);
                    m.CreatedOn = ConvertToUserTime(x.CreatedOnUtc, DateTimeKind.Utc);
                    m.ApprovedComments = _blogService.GetBlogCommentsCount(x, isApproved: true);
                    m.NotApprovedComments = _blogService.GetBlogCommentsCount(x, isApproved: false);

                    return m;
                }),
                Total = blogPosts.TotalCount
            };

            return Json(gridModel);
        }

        public virtual ActionResult Create()
        {
            var model = new AdminBlogPostModel();
            model.AllowComments = true;
            return View(model);
        }

        [HttpPost]
        public virtual ActionResult Create(AdminBlogPostModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var blogPost = new BlogPost();
                    blogPost.Title = model.Title;
                    blogPost.Tags = model.Tags;
                    blogPost.BodyOverview = model.BodyOverview.Trim();
                    blogPost.Body = HttpUtility.HtmlDecode(model.Body);
                    blogPost.AllowComments = model.AllowComments;
                    blogPost.StartDateUtc = model.StartDate;
                    blogPost.EndDateUtc = model.EndDate;
                    blogPost.CreatedOnUtc = DateTime.UtcNow;
                    _blogService.InsertBlogPost(blogPost);

                    SuccessNotification("The new blog post has been added successfully.");

                    return RedirectToAction("List");
                }
            }
            catch { }

            return View(model);
        }

        public virtual ActionResult Edit(int id)
        {
            var blogPost = _blogService.GetBlogPostById(id);
            if (blogPost == null)
                //No blog post found with the specified id
                return RedirectToAction("List");

            var model = new AdminBlogPostModel();
            model.Title = blogPost.Title;
            model.Tags = blogPost.Tags;
            model.BodyOverview = blogPost.BodyOverview.Trim();
            model.Body = blogPost.Body;
            model.AllowComments = blogPost.AllowComments;
            model.StartDate = blogPost.StartDateUtc;
            model.EndDate = blogPost.EndDateUtc;
            return View(model);
        }

        [HttpPost]
        public virtual ActionResult Edit(AdminBlogPostModel model)
        {
            try
            {
                var blogPost = _blogService.GetBlogPostById(model.Id);
                if (blogPost == null)
                    //No blog post found with the specified id
                    return RedirectToAction("List");

                if (ModelState.IsValid)
                {
                    blogPost.Title = model.Title;
                    blogPost.Tags = model.Tags;
                    blogPost.BodyOverview = model.BodyOverview.Trim();
                    blogPost.Body = HttpUtility.HtmlDecode(model.Body);
                    blogPost.AllowComments = model.AllowComments;
                    blogPost.StartDateUtc = model.StartDate;
                    blogPost.EndDateUtc = model.EndDate;
                    _blogService.UpdateBlogPost(blogPost);

                    SuccessNotification("The blog post has been updated successfully.");
                    return RedirectToAction("List");
                }
            }
            catch { }
            return View(model);
        }

        [HttpPost]
        public virtual ActionResult Delete(int id)
        {
            var blogPost = _blogService.GetBlogPostById(id);
            if (blogPost == null)
                //No blog post found with the specified id
                return RedirectToAction("List");

            _blogService.DeleteBlogPost(blogPost);

            SuccessNotification("The blog post has been deleted successfully.");
            return RedirectToAction("List");
        }

        #endregion

        #region Comments

        public virtual ActionResult Comments(int? filterByBlogPostId)
        {
            ViewBag.FilterByBlogPostId = filterByBlogPostId;
            var model = new AdminBlogCommentListModel();

            //"approved" property
            //0 - all
            //1 - approved only
            //2 - disapproved only
            model.AvailableApprovedOptions.Add(new SelectListItem { Text = "All", Value = "0" });
            model.AvailableApprovedOptions.Add(new SelectListItem { Text = "Approved", Value = "1" });
            model.AvailableApprovedOptions.Add(new SelectListItem { Text = "Disapproved", Value = "2" });

            return View(model);
        }

        [HttpPost]
        public virtual ActionResult Comments(int? filterByBlogPostId, DataSourceRequest command, AdminBlogCommentListModel model)
        {
            var createdOnFromValue = model.CreatedOnFrom == null ? null
                            : (DateTime?)ConvertToUtcTime(model.CreatedOnFrom.Value, INDIAN_ZONE_C);

            var createdOnToValue = model.CreatedOnTo == null ? null
                            : (DateTime?)ConvertToUtcTime(model.CreatedOnTo.Value, INDIAN_ZONE_C).AddDays(1);

            bool? approved = null;
            if (model.SearchApprovedId > 0)
                approved = model.SearchApprovedId == 1;

            var comments = _blogService.GetAllComments(null,filterByBlogPostId, approved, createdOnFromValue, createdOnToValue, model.SearchText);

            var gridModel = new DataSourceResult
            {
                Data = comments.PagedForCommand(command).Select(blogComment =>
                {
                    var commentModel = new AdminBlogCommentModel();
                    commentModel.Id = blogComment.Id;
                    commentModel.BlogPostId = blogComment.BlogPostId;
                    commentModel.BlogPostTitle = blogComment.BlogPost.Title;
                    commentModel.VisitorId = blogComment.VisitorId;
                    var customer = blogComment.Visitor;
                    commentModel.VisitorInfo = (customer != null) ? customer.Email : string.Empty;
                    commentModel.CreatedOn = ConvertToUserTime(blogComment.CreatedOnUtc, DateTimeKind.Utc);
                    commentModel.Comment = blogComment.CommentText;
                    commentModel.IsApproved = blogComment.IsApproved;

                    return commentModel;
                }),
                Total = comments.Count,
            };
            return Json(gridModel);
        }

        [HttpPost]
        public virtual ActionResult CommentUpdate(AdminBlogCommentModel model)
        {
            var comment = _blogService.GetBlogCommentById(model.Id);
            if (comment == null)
                throw new ArgumentException("No comment found with the specified id");

            var previousIsApproved = comment.IsApproved;

            comment.IsApproved = model.IsApproved;
            _blogService.UpdateBlogPostComment(comment);

            return new NullJsonResult();
        }

        public virtual ActionResult CommentDelete(int id)
        {
            var comment = _blogService.GetBlogCommentById(id);
            if (comment == null)
                throw new ArgumentException("No comment found with the specified id");

            var blogPost = comment.BlogPost;
            _blogService.DeleteBlogComment(comment);

            return new NullJsonResult();
        }

        [HttpPost]

DPTS/DPTS.Web/Views/AdminBlog/Create.cshtml
@model AdminBlogPostModel
@using DPTS.Web.Models;
@{    
    //page title
    ViewBag.Title = "Create Blog";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="content-header clearfix">
        <h2 class="pull-left">
            Add a new blog post
            <small><i class="fa fa-arrow-circle-left"></i>@Html.ActionLink("BackToList", "List")</small>
        </h2>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
             Save
            </button>
        
        </div>
    </div>
    @Html.Partial("_CreateOrUpdate", Model)
}

DPTS/DPTS.Web/Views/AdminBlog/Edit.cshtml
@model AdminBlogPostModel
@using DPTS.Web.Models;
@{    
    //page title
    ViewBag.Title = "EditBlogPostDetails";
    //active menu item (system name)
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="content-header clearfix">
        <h3 class="pull-left">
            Edit - @Model.Title
            <small><i class="fa fa-arrow-circle-left"></i>@Html.ActionLink("BackToList", "List")</small>
        </h3>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
               Save
            </button>
            @*<button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>*@
            <span id="blogpost-delete" class="btn bg-red">
                <i class="fa fa-trash-o"></i>
                 Delete
            </span>
        </div>
    </div>
    @Html.Partial("_CreateOrUpdate", Model)
}
@*@Html.DeleteConfirmation("blogpost-delete")*@

DPTS/DPTS.Web/Views/AdminBlog/List.cshtml
@using DPTS.Web.Helpers
@{
    //page title
    ViewBag.Title = "Blog Post";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
    Html.Assets().Styles.Add("/Content/kendo/2017.1.118/kendo.common-material.min.css");
    Html.Assets().Styles.Add("/Content/kendo/2017.1.118/kendo.material.min.css");
    Html.Assets().Styles.Add("/Content/kendo/2017.1.118/kendo.material.mobile.min.css");
}
<script src="~/Scripts/kendo/2017.1.118/jquery.min.js"></script>
<script src="~/Scripts/kendo/2017.1.118/kendo.all.min.js"></script>
@Html.AntiForgeryToken()
<div class="content-header clearfix">
    <h1 class="pull-left">
        Blog posts
    </h1>
    <div class="pull-right">
        <a href="@Url.Action("Create")" class="btn bg-blue">
            <i class="fa fa-plus-square"></i>
            AddNew
        </a>
    </div>
</div>

<div class="content">
    <div class="form-horizontal">
        <div class="panel-group">

            @*hide the entire search block if no elements are displayed*@
            @*<div class="panel panel-default panel-search" @(Model.AvailableStores.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group" @(Model.AvailableStores.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
                                <div class="col-md-4">
                                    @Html.NopLabelFor(model => model.SearchStoreId)
                                </div>
                                <div class="col-md-8">
                                    @Html.NopDropDownList("SearchStoreId", Model.AvailableStores)
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="button" id="search-blogpost" class="btn btn-primary btn-search">
                                        <i class="fa fa-search"></i>
                                        @T("Admin.Common.Search")
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>*@

            <div class="panel panel-default">
                <div class="panel-body">
                    <div id="blogpost-grid"></div>

                    <script>
                        $(document).ready(function() {
                            $("#blogpost-grid").kendoGrid({
                                dataSource: {
                                    type: "json",
                                    transport: {
                                        read: {
                                            url: "@Html.Raw(Url.Action("List", "AdminBlog"))",
                                            type: "POST",
                                            dataType: "json"
                                            //data: additionalData
                                        }
                                    },
                                    schema: {
                                        data: "Data",
                                        total: "Total",
                                        errors: "Errors"
                                    },
                                    error: function(e) {
                                        display_kendoui_grid_error(e);
                                        // Cancel the changes
                                        this.cancelChanges();
                                    },
                                    pageSize: 10,
                                    serverPaging: true,
                                    serverFiltering: true,
                                    serverSorting: true
                                },
                                pageable: {
                                    refresh: true,
                                    pageSizes: [10]
                                   // Html.Partial("_GridPagerMessages")
                                },
                                editable: {
                                    confirmation: "DeleteConfirmation",
                                    mode: "inline"
                                },
                                scrollable: false,
                                columns: [
                                {
                                    field: "Title",
                                    title: "Title"
                                },{
                                    title: "Comments",
                                    headerAttributes: { style: "text-align:center" },
                                    attributes: { style: "text-align:center" },
                                    template: '<a class="btn btn-default" href="Comments?filterByBlogPostId=#=Id#">Comments - #=ApprovedComments + NotApprovedComments# (#=NotApprovedComments#)</a>'
                                }, {
                                    field: "StartDate",
                                    title: "StartDate",
                                    width: 200,
                                    type: "date",
                                    format: "{0:G}"
                                }, {
                                    field: "EndDate",
                                    title: "EndDate",
                                    width: 200,
                                    type: "date",
                                    format: "{0:G}"
                                }, {
                                    field: "CreatedOn",
                                    title: "CreatedOn",
                                    width: 200,
                                    type: "date",
                                    format: "{0:G}"
                                }, {
                                    field: "Id",
                                    title: "Edit",
                                    width: 100,
                                    headerAttributes: { style: "text-align:center" },
                                    attributes: { style: "text-align:center" },
                                    template: '<a class="btn btn-default" href="Edit?id=#=Id#"><i class="fa fa-pencil"></i>Edit</a>'
                                    }
                                ]
                            });
                        });
                    </script>

                    <script type="text/javascript">
                        //$(document).ready(function() {
                        //    //search button
                        //    $('#search-blogpost').click(function() {
                        //        //search
                        //        var grid = $('#blogpost-grid').data('kendoGrid');
                        //        grid.dataSource.page(1); //new search. Set page size to 1
                        //        //grid.dataSource.read(); we already loaded the grid above using "page" function
                        //        return false;
                        //    });
                        //});

                        //function additionalData() {
                        //    var data = {
                        //        SearchStoreId: $('#SearchStoreId').val()
                        //    };
                        //    addAntiForgeryToken(data);
                        //    return data;
                        //}
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>

DPTS/DPTS.Web/Views/AdminBlog/_CreateOrUpdate.cshtml
@model AdminBlogPostModel
@using DPTS.Web.Models;
@using DPTS.Web.Helpers
@using System.Text;
@{ 
    // IBlogService _blogService;
    Html.Assets().Styles.Add("/Content/kendo/2017.1.118/kendo.common-material.min.css");
    Html.Assets().Styles.Add("/Content/kendo/2017.1.118/kendo.material.min.css");
    Html.Assets().Styles.Add("/Content/kendo/2017.1.118/kendo.material.mobile.min.css");
}
<script src="~/Scripts/kendo/2017.1.118/kendo.all.min.js"></script>

@{
//resources for product tags input
//Html.AppendCssFileParts("~/Administration/Content/tagEditor/jquery.tag-editor.css");
//Html.AppendScriptParts("~/Administration/Scripts/tagEditor/jquery.tag-editor.min.js");
//Html.AppendScriptParts("~/Administration/Scripts/tagEditor/jquery.caret.min.js");

//Html.Assets().Styles.Add("/Content/tagEditor/jquery.tag-editor.css");
//Html.Assets().Scripts.Add("/Scripts/tagEditor/jquery.tag-editor.min.js");
//Html.Assets().Scripts.Add("/Scripts/tagEditor/jquery.caret.min.js");
}


    @*<script type="text/javascript">
        @{
            //TODO move to Model
            var blogTags = _blogService.GetAllBlogPostTags(true);
            var blogTagsSb = new StringBuilder();
            blogTagsSb.Append("var initialBlogTags = [");
            for (int i = 0; i < blogTags.Count; i++)
            {
                var tag = blogTags[i];
                blogTagsSb.Append("'");
                blogTagsSb.Append(HttpUtility.JavaScriptStringEncode(tag.Name));
                blogTagsSb.Append("'");
                if (i != blogTags.Count - 1)
                {
                    blogTagsSb.Append(",");
                }
            }
            blogTagsSb.Append("]");
        }
        //tags
        $(document).ready(function() {
            @Html.Raw(blogTagsSb.ToString())
            $("#Tags").tagEditor({
                autocomplete: {
                    delay: 0,
                    position: { collision: 'flip' },
                    source: initialBlogTags
                },
                delimiter: ',',
                placeholder: 'Placeholder'
            });
        });
    </script>*@

@Html.ValidationSummary(true)
@Html.HiddenFor(model => model.Id)
<div class="content">
    <div class="form-horizontal">
        <div class="panel-group">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.Title)
                        </div>
                        <div class="col-md-9">
                            <input class="form-control" id="Title" name="Title" value="@Model.Title">
                            @Html.ValidationMessageFor(model => model.Title)
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.Body)
                        </div>
                        <div class="col-md-9">
                            @Html.TextAreaFor(model => model.Body, new { @class = "form-control" })
                            <script>
                            $(document).ready(function() {
                                // create Editor from textarea HTML element with default set of tools
                                $("#Body").kendoEditor({
                                    resizable: {
                                    content: true,
                                    toolbar: true
                                }});
                            });
                            </script>
                            @Html.ValidationMessageFor(model => model.Body)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.BodyOverview)
                        </div>
                        <div class="col-md-9">
                            @Html.TextAreaFor(model => model.BodyOverview,new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.BodyOverview)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.Tags)
                        </div>
                        <div class="col-md-9">
                            <input id="Tags" name="Tags" value="@Model.Tags" class="form-control" placeholder="Enter text">
                            <p class="help-block">Tag should be comma separated. e.g. Red,Blue..etc.</p>
                            @Html.ValidationMessageFor(model => model.Tags)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.StartDate)
                        </div>
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.StartDate)
                            @Html.ValidationMessageFor(model => model.StartDate)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.EndDate)
                        </div>
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.EndDate)
                            @Html.ValidationMessageFor(model => model.EndDate)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.AllowComments)
                        </div>
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.AllowComments)
                            @Html.ValidationMessageFor(model => model.AllowComments)
                        </div>
                    </div>
                  
                </div>
            </div>
        </div>
    </div>
</div>