DPTS/DPTS.Web/Models/EmailCategoryViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace DPTS.Web.Models
{
    public class EmailCategoryViewModel
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Name")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Use letters only please")]
        public string Name { get; set; }
 
        [Display(Name = "Published")]
        public bool Published { get; set; }

        [Display(Name = "Display Order")]
        public int DisplayOrder { get; set; }

        [Display(Name = "Date Created")]
        public DateTime DateCreated { get; set; }

        [Display(Name = "Date Updated")]
        public DateTime DateUpdated { get; set; }
    }
}

DPTS/DPTS.Web/Controllers/EmailCategoryController.cs
using DPTS.Web.Models;
using System.Linq;
using System.Web.Mvc;
using DPTS.Domain.Core.Notification;
using DPTS.Domain.Entities.Notification;

namespace DPTS.Web.Controllers
{
    [Authorize]
    public class EmailCategoryController : BaseController
    {
        #region Fields

        private readonly IEmailCategoryService _emailCategory;

        #endregion

        #region Contructor

        public EmailCategoryController(IEmailCategoryService emailCategoryService)
        {
            _emailCategory = emailCategoryService;
        }

        #endregion

        #region Methods

        public ActionResult List()
        {
            var countries = _emailCategory.GetAllEmailCategories(true);
            var model = countries.Select(c => new EmailCategoryViewModel
            {
                Id = c.Id,
                Name = c.Name,
                DisplayOrder = c.DisplayOrder,
                Published = c.Published
            }).ToList();
            return View(model);
        }

        public ActionResult Create()
        {
            var model = new EmailCategoryViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(EmailCategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                var country = new EmailCategory
                {
                    Name = model.Name,
                    Published = model.Published,
                    DisplayOrder = model.DisplayOrder
                };
                _emailCategory.InsertEmailCategory(country);
                return RedirectToAction("List");
            }
            return View(model);
        }

        public ActionResult Edit(int Id)
        {
            if (!IsValidateId(Id))
                return HttpNotFound();

            var country = _emailCategory.GetEmailCategoryById(Id);
            if (country == null)
                return HttpNotFound();

            var model = new EmailCategoryViewModel
            {
                Id = country.Id,
                Name = country.Name,
                DisplayOrder = country.DisplayOrder,
                Published = country.Published
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(EmailCategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                var country = _emailCategory.GetEmailCategoryById(model.Id);
                country.Id = model.Id;
                country.Name = model.Name;
                country.DisplayOrder = model.DisplayOrder;
                country.Published = model.Published;
                _emailCategory.UpdateEmailCategory(country);
                return RedirectToAction("List");
            }
            return View();
        }


        public ActionResult DeleteConfirmed(int id)
        {
            var country = _emailCategory.GetEmailCategoryById(id);
            if (country != null)
                _emailCategory.DeleteEmailCategory(country);


            return Content("Deleted");
        }

        #endregion
    }
}

DPTS/DPTS.Web/Views/EmailCategory/Create.cshtml
@using DPTS.Web.Models
@model EmailCategoryViewModel
@{
    ViewBag.Title = "Add - Email Category";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Add New</h1>
            <div class="pull-right" style="margin-top:-68px">
                <button type="submit" name="save" class="btn bg-blue" style="background-color:#0073b7;color:white">
                    <i class="fa fa-floppy-o"></i>
                    Save
                </button>
            </div>
           @Html.ActionLink("Back to List", "List")
        </div>
        <!-- /.col-lg-12 -->
    </div>
    @Html.Partial("_CreateOrUpdate", Model)
}

DPTS/DPTS.Web/Views/EmailCategory/Edit.cshtml
@using DPTS.Web.Models
@model EmailCategoryViewModel
@{
    ViewBag.Title = "Add - Email Category";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Edit - @Model.Name
            </h1>
            <div class="pull-right" style="margin-top:-68px">
                <button type="submit" name="save" class="btn bg-blue" style="background-color:#0073b7;color:white">
                    <i class="fa fa-floppy-o"></i>
                    Save
                </button>
            </div>
            @Html.ActionLink("Back to List", "List")
        </div>
    </div>
    @Html.Partial("_CreateOrUpdate", Model)
}

DPTS/DPTS.Web/Views/EmailCategory/List.cshtml
@using DPTS.Web.Models
@model IEnumerable<EmailCategoryViewModel>
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
    <link href="~/Content/Admin/vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">
    <!-- DataTables Responsive CSS -->
    <link href="~/Content/Admin/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet">
     
    int i = 1;
}

<div class="row">
    <div class="col-lg-12">
        <div class="pull-right-button">
            <a href="@Url.Action("Create","EmailCategory")" class="btn btn-primary">
                <i class="fa fa-plus-square"></i>
                Add new
            </a>
        </div>

        <h1 class="page-header">Email Category</h1>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Email Category
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table table-striped table-bordered table-hover" id="Spacility-list">
                                <thead>
                                    <tr>
                                        <th>
                                            Name
                                        </th> 
                                        <th>
                                            Display Order
                                        </th>
                                        
                                        <th>Published</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        if (i % 2 != 0)
                                        {
                                            <tr class="odd gradeX">
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Name)
                                                </td>
                                           
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.DisplayOrder)
                                                </td>
                                               
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Published)
                                                </td>
                                                <td>
                                                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                                    <a href="#" data-toggle="modal" data-target="#myModal" onclick="deleterecord(@item.Id,'EmailCategory')">Delete</a>
                                                </td>
                                            </tr>
                                        }
                                        else
                                        {
                                            <tr class="even gradeA">
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Name)
                                                </td>
                                            
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.DisplayOrder)
                                                </td> 
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Published)
                                                </td>
                                                <td>
                                                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                                    <a href="#" data-toggle="modal" data-target="#myModal" onclick="deleterecord(@item.Id,'EmailCategory')">Delete</a>
                                                </td>
                                            </tr>
                                        }
                                        i++;
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

DPTS/DPTS.Web/Views/EmailCategory/_CreateOrUpdate.cshtml
@using DPTS.Web.Models
@model EmailCategoryViewModel

@Html.ValidationSummary(true)
@Html.HiddenFor(model => model.Id)

<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-6">
                    <form role="form">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name)
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name)
                        </div>
                      
                        <div class="form-group">
                            @Html.LabelFor(model => model.DisplayOrder)
                            @Html.EditorFor(model => model.DisplayOrder, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DisplayOrder)
                        </div>
                        
                        <div class="form-group">
                            @Html.LabelFor(model => model.Published)
                            @Html.EditorFor(model => model.Published)
                            @Html.ValidationMessageFor(model => model.Published)
                        </div>
                        @if (Model.Id > 0)
                        {
                            <div class="form-group">
                                    @Html.LabelFor(model => model.DateUpdated)
                                    @Html.DisplayFor(model => model.DateCreated)
                            </div>
                        }
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>