DPTS/DPTS.Web/Models/DefaultNotificationSettingsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace DPTS.Web.Models
{
    public class DefaultNotificationSettingsViewModel
    {
        public DefaultNotificationSettingsViewModel()
        {
            AvailableEmailCategory = new List<SelectListItem>();
        }
        public int Id { get; set; } 
        [Display(Name = "Email Category")]
        public int EmailCategoryId { get; set; }

        public string EmailCategory { get; set; }

        [Required]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Display(Name = "Message")]
        public string Message { get; set; }

        [Display(Name = "Published")]
        public bool Published { get; set; }

        [Display(Name = "Display Order")]
        public int DisplayOrder { get; set; }

        [Display(Name = "Date Created")]
        public DateTime DateCreated { get; set; }


        [Display(Name = "Date Updated")]
        public DateTime DateUpdated { get; set; }

        public IList<SelectListItem> AvailableEmailCategory { get; set; }
    }
}

DPTS/DPTS.Web/Controllers/DefaultNotificationSettingsController.cs
using DPTS.Web.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using DPTS.Domain.Core.Notification;
using DPTS.Domain.Entities.Notification;

namespace DPTS.Web.Controllers
{
    [Authorize]
    public class DefaultNotificationSettingsController : BaseController
    {
        #region Fields

        private readonly IDefaultNotificationSettingsService _defaultNotificationSettingsService;
        private readonly IEmailCategoryService _emailCategoryService;

        #endregion

        #region Contructor

        public DefaultNotificationSettingsController(
            IDefaultNotificationSettingsService defaultNotificationSettingsService,
            IEmailCategoryService emailCategoryService)
        {
            _defaultNotificationSettingsService = defaultNotificationSettingsService;
            _emailCategoryService = emailCategoryService;
        }

        #endregion

        #region Utilities

        public IList<SelectListItem> GetDefaultNotificationSettings()
        {
            var emailCategories = _emailCategoryService.GetAllEmailCategories(true);
            var typelst = new List<SelectListItem>
            {
                new SelectListItem
                {
                    Text = "Select",
                    Value = "0"
                }
            };
            typelst.AddRange(emailCategories.ToList().Select(type => new SelectListItem
            {
                Text = type.Name,
                Value = type.Id.ToString()
            }));
            return typelst;
        }

        #endregion

        #region Methods

        public ActionResult List()
        {
            var defaultNotificationSettings = _defaultNotificationSettingsService.GetAllDefaultNotificationSettings(true);
            var model = defaultNotificationSettings.Select(c => new DefaultNotificationSettingsViewModel
            {
                Id = c.Id,
                Name = c.Name,
                EmailCategory = _emailCategoryService.GetEmailCategoryById(c.Id).Name,
                DisplayOrder = c.DisplayOrder,
                Message = c.Message,
                Published = c.Published,
                EmailCategoryId = c.CategoryId
            }).ToList();
            return View(model);
        }

        public ActionResult Create()
        {
            var model = new DefaultNotificationSettingsViewModel
            {
                AvailableEmailCategory = GetDefaultNotificationSettings()
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(DefaultNotificationSettingsViewModel model)
        {
            if (model.EmailCategoryId == 0)
                ModelState.AddModelError("", "select Email Category");

            if (ModelState.IsValid)
            {
                var stateProvince = new DefaultNotificationSettings
                {
                    Name = model.Name,
                    Published = model.Published,
                    DisplayOrder = model.DisplayOrder,
                    Message = model.Message,
                    CategoryId = model.EmailCategoryId
                };
                _defaultNotificationSettingsService.InsertDefaultNotificationSettings(stateProvince);
                return RedirectToAction("List");
            }
            model.AvailableEmailCategory = GetDefaultNotificationSettings();
            return View(model);
        }

        public ActionResult Edit(int Id)
        {
            if (!IsValidateId(Id))
                return HttpNotFound();

            var defaultNotificationSettings = _defaultNotificationSettingsService.GetDefaultNotificationSettingsById(Id);
            if (defaultNotificationSettings == null)
                return HttpNotFound();

            var model = new DefaultNotificationSettingsViewModel
            {
                Id = defaultNotificationSettings.Id,
                Name = defaultNotificationSettings.Name,
                EmailCategory = _emailCategoryService.GetEmailCategoryById(defaultNotificationSettings.Id).Name,
                DisplayOrder = defaultNotificationSettings.DisplayOrder,
                Published = defaultNotificationSettings.Published,
                EmailCategoryId = defaultNotificationSettings.CategoryId,
                Message = defaultNotificationSettings.Message,
                AvailableEmailCategory = GetDefaultNotificationSettings()
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(DefaultNotificationSettingsViewModel model)
        {
            if (ModelState.IsValid)
            {
                var stateProvince = _defaultNotificationSettingsService.GetDefaultNotificationSettingsById(model.Id);
                stateProvince.Id = model.Id;
                stateProvince.Name = model.Name;
                stateProvince.DisplayOrder = model.DisplayOrder;
                stateProvince.Published = model.Published;
                stateProvince.CategoryId = model.EmailCategoryId;
                stateProvince.Message = model.Message;

                _defaultNotificationSettingsService.UpdateDefaultNotificationSettings(stateProvince);
                return RedirectToAction("List");
            }
            model.AvailableEmailCategory = GetDefaultNotificationSettings();
            return View(model);
        }

        public ActionResult DeleteConfirmed(int id)
        {
            var defaultNotificationSettings = _defaultNotificationSettingsService.GetDefaultNotificationSettingsById(id);
            if (defaultNotificationSettings != null)
                _defaultNotificationSettingsService.DeleteDefaultNotificationSettings(defaultNotificationSettings);


            return Content("Deleted");
        }

        #endregion
    }
}

DPTS/DPTS.Web/Views/DefaultNotificationSettings/Create.cshtml
@using DPTS.Web.Models
@model DefaultNotificationSettingsViewModel
@{
    ViewBag.Title = "add - Default Notification Settings";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Add New</h1>
            <div class="pull-right" style="margin-top:-68px">
                <button type="submit" name="save" class="btn bg-blue" style="background-color:#0073b7;color:white">
                    <i class="fa fa-floppy-o"></i>
                    Save
                </button>
            </div>
           @Html.ActionLink("Back to List", "List")
        </div>
        <!-- /.col-lg-12 -->
    </div>
    @Html.Partial("_CreateOrUpdate", Model)
}

DPTS/DPTS.Web/Views/DefaultNotificationSettings/Edit.cshtml
@using DPTS.Web.Models
@model DefaultNotificationSettingsViewModel
@{
    ViewBag.Title = "add - Default Notification Settings";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Edit - @Model.Name
            </h1>
            <div class="pull-right" style="margin-top:-68px">
                <button type="submit" name="save" class="btn bg-blue" style="background-color:#0073b7;color:white">
                    <i class="fa fa-floppy-o"></i>
                    Save
                </button>
            </div>
            @Html.ActionLink("Back to List", "List")
        </div>
    </div>
    @Html.Partial("_CreateOrUpdate", Model)
}

DPTS/DPTS.Web/Views/DefaultNotificationSettings/List.cshtml
@using DPTS.Web.Models
@model IEnumerable<DefaultNotificationSettingsViewModel>
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
    <link href="~/Content/Admin/vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">
    <!-- DataTables Responsive CSS -->
    <link href="~/Content/Admin/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet">

    int i = 1;
}

<div class="row">
    <div class="col-lg-12">
        <div class="pull-right-button">
            <a href="@Url.Action("Create","DefaultNotificationSettings")" class="btn btn-primary">
                <i class="fa fa-plus-square"></i>
                Add new
            </a>
        </div>

        <h1 class="page-header">  Default Notification Settings</h1>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Default Notification Settings
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table table-striped table-bordered table-hover" id="Spacility-list">
                                <thead>
                                    <tr>
                                        <th>
                                            Name
                                        </th>
                                        <th>
                                            Email Category
                                        </th>
                                        <th>
                                            Message
                                        </th>
                                        <th>
                                            Display Order
                                        </th>
                                        <th>
                                            Published
                                        </th>
                                        <th>
                                            Action
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        if (i % 2 != 0)
                                        {
                                            <tr class="odd gradeX">
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Name)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.EmailCategory)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Message)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.DisplayOrder)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Published)
                                                </td>
                                                <td>
                                                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                                    <a href="#" data-toggle="modal" data-target="#myModal" onclick="deleterecord(@item.Id,'DefaultNotificationSettings')">Delete</a>
                                                </td>
                                            </tr>
                                        }
                                        else
                                        {
                                            <tr class="even gradeA">
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Name)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.EmailCategory)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Message)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.DisplayOrder)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Published)
                                                </td>
                                                <td>
                                                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                                    <a href="#" data-toggle="modal" data-target="#myModal" onclick="deleterecord(@item.Id,'DefaultNotificationSettings')">Delete</a>
                                                </td>
                                            </tr>
                                        }
                                        i++;
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

DPTS/DPTS.Web/Views/DefaultNotificationSettings/_CreateOrUpdate.cshtml
@using DPTS.Web.Models
@model DefaultNotificationSettingsViewModel

@Html.ValidationSummary(true)
@Html.HiddenFor(model => model.id)

<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-6">
                    <form role="form">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name)
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name)
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.EmailCategoryid)
                            @Html.DropDownListFor(model => model.EmailCategoryid, Model.AvailableEmailCategory,new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.EmailCategoryid, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Message)
                            @Html.TextAreaFor(model => model.Message,  new { style = "min-width:500px;", htmlAttributes = new { @class = "form-control"  } })
                            @Html.ValidationMessageFor(model => model.Message)
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.DisplayOrder)
                            @Html.EditorFor(model => model.DisplayOrder, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DisplayOrder)
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Published)
                            @Html.EditorFor(model => model.Published, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Published)
                        </div>
                        @if (Model.Id > 0)
                        {
                            <div class="form-group">
                                    @Html.LabelFor(model => model.DateUpdated)
                                    @Html.DisplayFor(model => model.DateCreated)
                            </div>
                        }
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>